services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5328:5328"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/eunoia
      - SECRET_KEY=your_secret_key_here
      - DEBUG=False
      - OPENAI_API_KEY=${OPENAI_API_KEY:-sk-dummy-key-for-development}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eunoia
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
