[tool.ruff]
target-version = "py311"
line-length = 128
indent-width = 4
exclude = [
    ".git",
    ".venv",
    "node_modules",
    "__pycache__",
]

# Rules to enable
[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
    "UP", # pyupgrade
    "B",  # flake8-bugbear
]

ignore = ["E501"]
fixable = ["ALL"]
unfixable = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto" 
